/**
 * Curated fallback image pool for campaign hero images.
 *
 * When an external hero image fails to load (403/404/timeout),
 * CampaignHeroImage picks a contextually appropriate stock photo
 * from this pool based on the campaign category.
 *
 * Auto-generated by: scripts/generate-fallback-pool.ts
 * Sources: Unsplash (primary), Pexels (fallback)
 * Regenerate: npx tsx scripts/generate-fallback-pool.ts
 *
 * Total: 115 images across 23 categories
 */

export interface FallbackImage {
  url: string;
  attribution: string;
}

const POOL: Record<string, FallbackImage[]> = {
  "medical": [
    {
      "url": "https://images.unsplash.com/photo-1669413453894-db3901ffdbc1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxob3NwaXRhbCUyMHBhdGllbnQlMjByZWNvdmVyeSUyMGhvcGUlMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1MzJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Valentin Fernandez on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1550792404-f62d4ce3bb3e?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxob3NwaXRhbCUyMHBhdGllbnQlMjByZWNvdmVyeSUyMGhvcGUlMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1MzJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alexander Grey on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1550791871-0bcd47c97881?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxob3NwaXRhbCUyMHBhdGllbnQlMjByZWNvdmVyeSUyMGhvcGUlMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1MzJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alexander Grey on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1755190666668-b2d77ca9b16f?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxob3NwaXRhbCUyMHBhdGllbnQlMjByZWNvdmVyeSUyMGhvcGUlMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1MzJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by maks_d on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1606166187734-a4cb74079037?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxob3NwaXRhbCUyMHBhdGllbnQlMjByZWNvdmVyeSUyMGhvcGUlMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1MzJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alexander Grey on Unsplash"
    }
  ],
  "disaster": [
    {
      "url": "https://images.unsplash.com/photo-1764116858740-832d0f86b86b?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxjb21tdW5pdHklMjByZWJ1aWxkaW5nJTIwYWZ0ZXIlMjBkaXNhc3RlciUyMGhvcGV8ZW58MXwwfHx8MTc3NjIyNjUzM3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Zoshua Colah on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1719993916887-373a139c495e?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxjb21tdW5pdHklMjByZWJ1aWxkaW5nJTIwYWZ0ZXIlMjBkaXNhc3RlciUyMGhvcGV8ZW58MXwwfHx8MTc3NjIyNjUzM3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Shubham Nayak on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1710397659596-67e96fec5b86?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxjb21tdW5pdHklMjByZWJ1aWxkaW5nJTIwYWZ0ZXIlMjBkaXNhc3RlciUyMGhvcGV8ZW58MXwwfHx8MTc3NjIyNjUzM3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Nacho Gimeno Guerrero on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1616680214429-d79397e56688?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxjb21tdW5pdHklMjByZWJ1aWxkaW5nJTIwYWZ0ZXIlMjBkaXNhc3RlciUyMGhvcGV8ZW58MXwwfHx8MTc3NjIyNjUzM3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by OCG Saving The Ocean on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1551883900-3731006009a0?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxjb21tdW5pdHklMjByZWJ1aWxkaW5nJTIwYWZ0ZXIlMjBkaXNhc3RlciUyMGhvcGV8ZW58MXwwfHx8MTc3NjIyNjUzM3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Trust \"Tru\" Katsande on Unsplash"
    }
  ],
  "military": [
    {
      "url": "https://images.unsplash.com/photo-1762855378807-21d97d6be181?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxtaWxpdGFyeSUyMGZhbWlseSUyMHNlcnZpY2UlMjBob25vciUyMHRyaWJ1dGV8ZW58MXwwfHx8MTc3NjIyNjUzNHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Richard Burlton on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1682623764495-bf042fa18a9b?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxtaWxpdGFyeSUyMGZhbWlseSUyMHNlcnZpY2UlMjBob25vciUyMHRyaWJ1dGV8ZW58MXwwfHx8MTc3NjIyNjUzNHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Wesley Tingey on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1509046948809-cee7c67dc810?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxtaWxpdGFyeSUyMGZhbWlseSUyMHNlcnZpY2UlMjBob25vciUyMHRyaWJ1dGV8ZW58MXwwfHx8MTc3NjIyNjUzNHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Spencer Imbrock on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1682623764505-2090c0cd7e41?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxtaWxpdGFyeSUyMGZhbWlseSUyMHNlcnZpY2UlMjBob25vciUyMHRyaWJ1dGV8ZW58MXwwfHx8MTc3NjIyNjUzNHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Wesley Tingey on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1682623764612-2e96debe9b9e?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxtaWxpdGFyeSUyMGZhbWlseSUyMHNlcnZpY2UlMjBob25vciUyMHRyaWJ1dGV8ZW58MXwwfHx8MTc3NjIyNjUzNHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Wesley Tingey on Unsplash"
    }
  ],
  "veterans": [
    {
      "url": "https://images.unsplash.com/photo-1769854549138-3176e1daf438?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHx2ZXRlcmFuJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMG5ldyUyMGJlZ2lubmluZ3xlbnwxfDB8fHwxNzc2MjI2NTM1fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by DJ Paine on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1760674899285-3954270346a0?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHx2ZXRlcmFuJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMG5ldyUyMGJlZ2lubmluZ3xlbnwxfDB8fHwxNzc2MjI2NTM1fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by yasmin peyman on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1774300916087-69bc63ed728d?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHx2ZXRlcmFuJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMG5ldyUyMGJlZ2lubmluZ3xlbnwxfDB8fHwxNzc2MjI2NTM1fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Driscoll-Peca Real Esate Team on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1615980215756-4d6069d4e872?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHx2ZXRlcmFuJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMG5ldyUyMGJlZ2lubmluZ3xlbnwxfDB8fHwxNzc2MjI2NTM1fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Pavel Gardavsky on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769933415641-bc651e0cb3f9?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHx2ZXRlcmFuJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMG5ldyUyMGJlZ2lubmluZ3xlbnwxfDB8fHwxNzc2MjI2NTM1fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by DJ Paine on Unsplash"
    }
  ],
  "memorial": [
    {
      "url": "https://images.unsplash.com/photo-1762037634131-2946e91bad04?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxtZW1vcmlhbCUyMGNhbmRsZXMlMjBmbG93ZXJzJTIwdHJpYnV0ZSUyMHJlbWVtYnJhbmNlfGVufDF8MHx8fDE3NzYyMjY1MzV8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitalii Onyshchuk on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1638937461270-c3f9017826b0?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxtZW1vcmlhbCUyMGNhbmRsZXMlMjBmbG93ZXJzJTIwdHJpYnV0ZSUyMHJlbWVtYnJhbmNlfGVufDF8MHx8fDE3NzYyMjY1MzV8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Rafiee Artist on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1591641342857-c0260dd8c73f?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxtZW1vcmlhbCUyMGNhbmRsZXMlMjBmbG93ZXJzJTIwdHJpYnV0ZSUyMHJlbWVtYnJhbmNlfGVufDF8MHx8fDE3NzYyMjY1MzV8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Andrew Valdivia on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1762990006179-1d8d7c05eb89?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxtZW1vcmlhbCUyMGNhbmRsZXMlMjBmbG93ZXJzJTIwdHJpYnV0ZSUyMHJlbWVtYnJhbmNlfGVufDF8MHx8fDE3NzYyMjY1MzV8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Valentin Karisch on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1567429159673-27bb8e200dd4?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxtZW1vcmlhbCUyMGNhbmRsZXMlMjBmbG93ZXJzJTIwdHJpYnV0ZSUyMHJlbWVtYnJhbmNlfGVufDF8MHx8fDE3NzYyMjY1MzV8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Soroush H. Zargarbashi on Unsplash"
    }
  ],
  "first-responders": [
    {
      "url": "https://images.unsplash.com/photo-1741119064982-c740f83dbc3e?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxmaXJlZmlnaHRlciUyMGhlcm8lMjBlbWVyZ2VuY3klMjBzZXJ2aWNlJTIwY291cmFnZXxlbnwxfDB8fHwxNzc2MjI2NTM2fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Jarden Bellamkonda on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1739902718882-a3f7e3424cab?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxmaXJlZmlnaHRlciUyMGhlcm8lMjBlbWVyZ2VuY3klMjBzZXJ2aWNlJTIwY291cmFnZXxlbnwxfDB8fHwxNzc2MjI2NTM2fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by León Films on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1504850012971-3dc85a46dc4a?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxmaXJlZmlnaHRlciUyMGhlcm8lMjBlbWVyZ2VuY3klMjBzZXJ2aWNlJTIwY291cmFnZXxlbnwxfDB8fHwxNzc2MjI2NTM2fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Hamza El-Falah on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1713689824350-929a848279c4?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxmaXJlZmlnaHRlciUyMGhlcm8lMjBlbWVyZ2VuY3klMjBzZXJ2aWNlJTIwY291cmFnZXxlbnwxfDB8fHwxNzc2MjI2NTM2fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Look Studio on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1654527288084-bce1ee2ccfdd?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxmaXJlZmlnaHRlciUyMGhlcm8lMjBlbWVyZ2VuY3klMjBzZXJ2aWNlJTIwY291cmFnZXxlbnwxfDB8fHwxNzc2MjI2NTM2fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by (Augustin-Foto) Jonas Augustin on Unsplash"
    }
  ],
  "community": [
    {
      "url": "https://images.unsplash.com/photo-1758599668429-121d54188b9c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxuZWlnaGJvcnMlMjBoZWxwaW5nJTIwY29tbXVuaXR5JTIwdm9sdW50ZWVyaW5nJTIwdG9nZXRoZXJ8ZW58MXwwfHx8MTc3NjIyNjUzN3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1593113598332-cd288d649433?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxuZWlnaGJvcnMlMjBoZWxwaW5nJTIwY29tbXVuaXR5JTIwdm9sdW50ZWVyaW5nJTIwdG9nZXRoZXJ8ZW58MXwwfHx8MTc3NjIyNjUzN3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Joel Muniz on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599667718-684569efe224?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxuZWlnaGJvcnMlMjBoZWxwaW5nJTIwY29tbXVuaXR5JTIwdm9sdW50ZWVyaW5nJTIwdG9nZXRoZXJ8ZW58MXwwfHx8MTc3NjIyNjUzN3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1601566674556-3ac2a27fec9f?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxuZWlnaGJvcnMlMjBoZWxwaW5nJTIwY29tbXVuaXR5JTIwdm9sdW50ZWVyaW5nJTIwdG9nZXRoZXJ8ZW58MXwwfHx8MTc3NjIyNjUzN3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Richard Burlton on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668337-58bfa42683ce?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxuZWlnaGJvcnMlMjBoZWxwaW5nJTIwY29tbXVuaXR5JTIwdm9sdW50ZWVyaW5nJTIwdG9nZXRoZXJ8ZW58MXwwfHx8MTc3NjIyNjUzN3ww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    }
  ],
  "essential-needs": [
    {
      "url": "https://images.unsplash.com/photo-1559748059-8a0665dae088?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxmb29kJTIwYmFuayUyMHNoZWx0ZXIlMjBodW1hbml0YXJpYW4lMjBhaWQlMjB3YXJtdGh8ZW58MXwwfHx8MTc3NjIyNjUzOHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by mostafa meraji on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1561673879-297ac83cafc7?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxmb29kJTIwYmFuayUyMHNoZWx0ZXIlMjBodW1hbml0YXJpYW4lMjBhaWQlMjB3YXJtdGh8ZW58MXwwfHx8MTc3NjIyNjUzOHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Madina Binti Umar on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1637034132661-4f015591b84a?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxmb29kJTIwYmFuayUyMHNoZWx0ZXIlMjBodW1hbml0YXJpYW4lMjBhaWQlMjB3YXJtdGh8ZW58MXwwfHx8MTc3NjIyNjUzOHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Wanman uthmaniyyah on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1559735442-535a7c982953?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxmb29kJTIwYmFuayUyMHNoZWx0ZXIlMjBodW1hbml0YXJpYW4lMjBhaWQlMjB3YXJtdGh8ZW58MXwwfHx8MTc3NjIyNjUzOHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by mostafa meraji on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1517137916198-332dd1c41fc6?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxmb29kJTIwYmFuayUyMHNoZWx0ZXIlMjBodW1hbml0YXJpYW4lMjBhaWQlMjB3YXJtdGh8ZW58MXwwfHx8MTc3NjIyNjUzOHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Annie Spratt on Unsplash"
    }
  ],
  "emergency": [
    {
      "url": "https://images.unsplash.com/photo-1596450514537-fae68a81346b?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxlbWVyZ2VuY3klMjByZWxpZWYlMjBjcmlzaXMlMjBoZWxwaW5nJTIwaGFuZHN8ZW58MXwwfHx8MTc3NjIyNjUzOXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Ashwini Chaudhary(Monty) on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1633889976313-c3192ab99116?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxlbWVyZ2VuY3klMjByZWxpZWYlMjBjcmlzaXMlMjBoZWxwaW5nJTIwaGFuZHN8ZW58MXwwfHx8MTc3NjIyNjUzOXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Rupinder Singh on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1616610269931-04d58b579ddf?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxlbWVyZ2VuY3klMjByZWxpZWYlMjBjcmlzaXMlMjBoZWxwaW5nJTIwaGFuZHN8ZW58MXwwfHx8MTc3NjIyNjUzOXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by mohammad samir on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1596522868339-a476e327e5e2?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxlbWVyZ2VuY3klMjByZWxpZWYlMjBjcmlzaXMlMjBoZWxwaW5nJTIwaGFuZHN8ZW58MXwwfHx8MTc3NjIyNjUzOXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Ashwini Chaudhary(Monty) on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1710093072228-8c3129f27357?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxlbWVyZ2VuY3klMjByZWxpZWYlMjBjcmlzaXMlMjBoZWxwaW5nJTIwaGFuZHN8ZW58MXwwfHx8MTc3NjIyNjUzOXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Khalil Radi on Unsplash"
    }
  ],
  "charity": [
    {
      "url": "https://images.unsplash.com/photo-1593113616828-6f22bca04804?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxjaGFyaXR5JTIwdm9sdW50ZWVycyUyMGRvbmF0aW9uJTIwZ2l2aW5nJTIwZ2VuZXJvc2l0eXxlbnwxfDB8fHwxNzc2MjI2NTQwfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Joel Muniz on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1628717341663-0007b0ee2597?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxjaGFyaXR5JTIwdm9sdW50ZWVycyUyMGRvbmF0aW9uJTIwZ2l2aW5nJTIwZ2VuZXJvc2l0eXxlbnwxfDB8fHwxNzc2MjI2NTQwfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Ismael Paramo on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1560220604-1985ebfe28b1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxjaGFyaXR5JTIwdm9sdW50ZWVycyUyMGRvbmF0aW9uJTIwZ2l2aW5nJTIwZ2VuZXJvc2l0eXxlbnwxfDB8fHwxNzc2MjI2NTQwfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Rashpal Singh on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1732800577634-f2e5c4d43995?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxjaGFyaXR5JTIwdm9sdW50ZWVycyUyMGRvbmF0aW9uJTIwZ2l2aW5nJTIwZ2VuZXJvc2l0eXxlbnwxfDB8fHwxNzc2MjI2NTQwfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Deski Jayantoro on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668429-121d54188b9c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxjaGFyaXR5JTIwdm9sdW50ZWVycyUyMGRvbmF0aW9uJTIwZ2l2aW5nJTIwZ2VuZXJvc2l0eXxlbnwxfDB8fHwxNzc2MjI2NTQwfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    }
  ],
  "education": [
    {
      "url": "https://images.unsplash.com/photo-1647596325805-3255398c7ba8?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxzdHVkZW50JTIwZWR1Y2F0aW9uJTIwc2Nob2xhcnNoaXAlMjBsZWFybmluZyUyMGdyb3d0aHxlbnwxfDB8fHwxNzc2MjI2NTQxfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Harati Project on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1750379046723-5ed69ff11571?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxzdHVkZW50JTIwZWR1Y2F0aW9uJTIwc2Nob2xhcnNoaXAlMjBsZWFybmluZyUyMGdyb3d0aHxlbnwxfDB8fHwxNzc2MjI2NTQxfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Zanyar Ibrahim on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1537539305875-d15d17683401?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxzdHVkZW50JTIwZWR1Y2F0aW9uJTIwc2Nob2xhcnNoaXAlMjBsZWFybmluZyUyMGdyb3d0aHxlbnwxfDB8fHwxNzc2MjI2NTQxfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by I Yogi on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769159522162-335b60c8146a?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxzdHVkZW50JTIwZWR1Y2F0aW9uJTIwc2Nob2xhcnNoaXAlMjBsZWFybmluZyUyMGdyb3d0aHxlbnwxfDB8fHwxNzc2MjI2NTQxfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Babak Eshaghian on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1678340458985-cf27b4a52c7c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxzdHVkZW50JTIwZWR1Y2F0aW9uJTIwc2Nob2xhcnNoaXAlMjBsZWFybmluZyUyMGdyb3d0aHxlbnwxfDB8fHwxNzc2MjI2NTQxfDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Jantri Simbolon on Unsplash"
    }
  ],
  "animal": [
    {
      "url": "https://images.unsplash.com/photo-1693956878294-f8b71c5d42f3?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxyZXNjdWUlMjBkb2clMjBjYXQlMjBzaGVsdGVyJTIwYWRvcHRpb24lMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1NDJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Rhodi Lopez on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1709364529489-d2562bc487b9?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxyZXNjdWUlMjBkb2clMjBjYXQlMjBzaGVsdGVyJTIwYWRvcHRpb24lMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1NDJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Duc Van on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1572152666560-5e7746e843eb?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxyZXNjdWUlMjBkb2clMjBjYXQlMjBzaGVsdGVyJTIwYWRvcHRpb24lMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1NDJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Danae Callister on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1774815588871-c2d858a0d068?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxyZXNjdWUlMjBkb2clMjBjYXQlMjBzaGVsdGVyJTIwYWRvcHRpb24lMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1NDJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Sergej Karpow on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1737048550427-0a7955fba776?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxyZXNjdWUlMjBkb2clMjBjYXQlMjBzaGVsdGVyJTIwYWRvcHRpb24lMjBjb21wYXNzaW9ufGVufDF8MHx8fDE3NzYyMjY1NDJ8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Jackie Best on Unsplash"
    }
  ],
  "environment": [
    {
      "url": "https://images.unsplash.com/photo-1763856957026-a74ab4f05891?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxuYXR1cmUlMjBjb25zZXJ2YXRpb24lMjBlYXJ0aCUyMGdyZWVuJTIwc3VzdGFpbmFiaWxpdHl8ZW58MXwwfHx8MTc3NjIyNjU0Mnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Ana Jovanovski on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668356-c8c919e24dda?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxuYXR1cmUlMjBjb25zZXJ2YXRpb24lMjBlYXJ0aCUyMGdyZWVuJTIwc3VzdGFpbmFiaWxpdHl8ZW58MXwwfHx8MTc3NjIyNjU0Mnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599669327-83d310882929?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxuYXR1cmUlMjBjb25zZXJ2YXRpb24lMjBlYXJ0aCUyMGdyZWVuJTIwc3VzdGFpbmFiaWxpdHl8ZW58MXwwfHx8MTc3NjIyNjU0Mnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1759044420896-f947fa7505c7?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxuYXR1cmUlMjBjb25zZXJ2YXRpb24lMjBlYXJ0aCUyMGdyZWVuJTIwc3VzdGFpbmFiaWxpdHl8ZW58MXwwfHx8MTc3NjIyNjU0Mnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Hugh Whyte on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1760992004120-19b7a726d2c6?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxuYXR1cmUlMjBjb25zZXJ2YXRpb24lMjBlYXJ0aCUyMGdyZWVuJTIwc3VzdGFpbmFiaWxpdHl8ZW58MXwwfHx8MTc3NjIyNjU0Mnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alba Calbetó on Unsplash"
    }
  ],
  "business": [
    {
      "url": "https://images.unsplash.com/photo-1654609065916-747b61fee962?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxzbWFsbCUyMGJ1c2luZXNzJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMHN0YXJ0dXB8ZW58MXwwfHx8MTc3NjIyNjU0NHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Operators Guild on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769618097114-0157e3d227d1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxzbWFsbCUyMGJ1c2luZXNzJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMHN0YXJ0dXB8ZW58MXwwfHx8MTc3NjIyNjU0NHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Olek Buzunov on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1586864387507-c7761c02bc37?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxzbWFsbCUyMGJ1c2luZXNzJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMHN0YXJ0dXB8ZW58MXwwfHx8MTc3NjIyNjU0NHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by iMattSmart on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1725203653086-b774ec111109?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxzbWFsbCUyMGJ1c2luZXNzJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMHN0YXJ0dXB8ZW58MXwwfHx8MTc3NjIyNjU0NHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by UNICEF on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1596754860837-506f408b0a8e?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxzbWFsbCUyMGJ1c2luZXNzJTIwY29tbXVuaXR5JTIwc3VwcG9ydCUyMHN0YXJ0dXB8ZW58MXwwfHx8MTc3NjIyNjU0NHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Kvnga on Unsplash"
    }
  ],
  "competition": [
    {
      "url": "https://images.unsplash.com/photo-1770237710686-ad2912589aca?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxhdGhsZXRpYyUyMGRldGVybWluYXRpb24lMjB5b3V0aCUyMHNwb3J0cyUyMGNvbXBldGl0aW9ufGVufDF8MHx8fDE3NzYyMjY1NDR8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Gurdaas Malik on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1773949107948-ba450784eeec?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxhdGhsZXRpYyUyMGRldGVybWluYXRpb24lMjB5b3V0aCUyMHNwb3J0cyUyMGNvbXBldGl0aW9ufGVufDF8MHx8fDE3NzYyMjY1NDR8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Peter Zhan on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1766525064566-80fba50c52cf?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxhdGhsZXRpYyUyMGRldGVybWluYXRpb24lMjB5b3V0aCUyMHNwb3J0cyUyMGNvbXBldGl0aW9ufGVufDF8MHx8fDE3NzYyMjY1NDR8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alfonso Scarpa on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1770237710597-a3ded3ecb3f7?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxhdGhsZXRpYyUyMGRldGVybWluYXRpb24lMjB5b3V0aCUyMHNwb3J0cyUyMGNvbXBldGl0aW9ufGVufDF8MHx8fDE3NzYyMjY1NDR8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Gurdaas Malik on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1770669564689-d3e8ec8d1595?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxhdGhsZXRpYyUyMGRldGVybWluYXRpb24lMjB5b3V0aCUyMHNwb3J0cyUyMGNvbXBldGl0aW9ufGVufDF8MHx8fDE3NzYyMjY1NDR8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Gurdaas Malik on Unsplash"
    }
  ],
  "creative": [
    {
      "url": "https://images.unsplash.com/photo-1769432402019-9140059e3573?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxhcnQlMjBjcmVhdGl2ZSUyMGV4cHJlc3Npb24lMjBpbnNwaXJhdGlvbiUyMGN1bHR1cmV8ZW58MXwwfHx8MTc3NjIyNjU0NXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Elena Mozhvilo on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1759577170752-440de7731e1c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxhcnQlMjBjcmVhdGl2ZSUyMGV4cHJlc3Npb24lMjBpbnNwaXJhdGlvbiUyMGN1bHR1cmV8ZW58MXwwfHx8MTc3NjIyNjU0NXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by lhon karwan on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769103311700-7a0fa29d505a?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxhcnQlMjBjcmVhdGl2ZSUyMGV4cHJlc3Npb24lMjBpbnNwaXJhdGlvbiUyMGN1bHR1cmV8ZW58MXwwfHx8MTc3NjIyNjU0NXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Eric Prouzet on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1746003625450-38b8d7c83969?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxhcnQlMjBjcmVhdGl2ZSUyMGV4cHJlc3Npb24lMjBpbnNwaXJhdGlvbiUyMGN1bHR1cmV8ZW58MXwwfHx8MTc3NjIyNjU0NXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Leonardo Iribe on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769905226622-bfcfce2be827?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxhcnQlMjBjcmVhdGl2ZSUyMGV4cHJlc3Npb24lMjBpbnNwaXJhdGlvbiUyMGN1bHR1cmV8ZW58MXwwfHx8MTc3NjIyNjU0NXww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Blessfield John on Unsplash"
    }
  ],
  "event": [
    {
      "url": "https://images.unsplash.com/photo-1769837231004-497d93ae155c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxjb21tdW5pdHklMjBnYXRoZXJpbmclMjBjZWxlYnJhdGlvbiUyMGZ1bmRyYWlzZXJ8ZW58MXwwfHx8MTc3NjIyNjU0Nnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by DJ Paine on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769837229979-950eed776ed7?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxjb21tdW5pdHklMjBnYXRoZXJpbmclMjBjZWxlYnJhdGlvbiUyMGZ1bmRyYWlzZXJ8ZW58MXwwfHx8MTc3NjIyNjU0Nnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by DJ Paine on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769867628383-d43f11114329?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxjb21tdW5pdHklMjBnYXRoZXJpbmclMjBjZWxlYnJhdGlvbiUyMGZ1bmRyYWlzZXJ8ZW58MXwwfHx8MTc3NjIyNjU0Nnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Olek Buzunov on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769867629367-188c760f3150?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxjb21tdW5pdHklMjBnYXRoZXJpbmclMjBjZWxlYnJhdGlvbiUyMGZ1bmRyYWlzZXJ8ZW58MXwwfHx8MTc3NjIyNjU0Nnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Olek Buzunov on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1769867628631-9fc91773d9e5?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxjb21tdW5pdHklMjBnYXRoZXJpbmclMjBjZWxlYnJhdGlvbiUyMGZ1bmRyYWlzZXJ8ZW58MXwwfHx8MTc3NjIyNjU0Nnww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Olek Buzunov on Unsplash"
    }
  ],
  "faith": [
    {
      "url": "https://images.unsplash.com/photo-1762707222259-8f3afdcf9359?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxjaHVyY2glMjBjb21tdW5pdHklMjBwcmF5ZXIlMjBzcGlyaXR1YWwlMjBkZXZvdGlvbnxlbnwxfDB8fHwxNzc2MjI2NTQ3fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by AMONWAT DUMKRUT on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1759592702526-991da137e08c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxjaHVyY2glMjBjb21tdW5pdHklMjBwcmF5ZXIlMjBzcGlyaXR1YWwlMjBkZXZvdGlvbnxlbnwxfDB8fHwxNzc2MjI2NTQ3fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Ray Kim on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1765947382522-ca6d359af08c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxjaHVyY2glMjBjb21tdW5pdHklMjBwcmF5ZXIlMjBzcGlyaXR1YWwlMjBkZXZvdGlvbnxlbnwxfDB8fHwxNzc2MjI2NTQ3fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Samuel Lopez Cruz on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1768009808770-89619e312ee6?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxjaHVyY2glMjBjb21tdW5pdHklMjBwcmF5ZXIlMjBzcGlyaXR1YWwlMjBkZXZvdGlvbnxlbnwxfDB8fHwxNzc2MjI2NTQ3fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by C.F. Photography on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1759860709000-8d77448bcdf1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxjaHVyY2glMjBjb21tdW5pdHklMjBwcmF5ZXIlMjBzcGlyaXR1YWwlMjBkZXZvdGlvbnxlbnwxfDB8fHwxNzc2MjI2NTQ3fDA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Tymofii Tarasov on Unsplash"
    }
  ],
  "family": [
    {
      "url": "https://images.unsplash.com/photo-1598967389784-a32c23b7c6ea?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxmYW1pbHklMjB0b2dldGhlciUyMGhvbWUlMjBjaGlsZHJlbiUyMGxvdmUlMjBib25kfGVufDF8MHx8fDE3NzYyMjY1NDh8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Russell Sutherland on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1658843352759-1fa2796affb8?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxmYW1pbHklMjB0b2dldGhlciUyMGhvbWUlMjBjaGlsZHJlbiUyMGxvdmUlMjBib25kfGVufDF8MHx8fDE3NzYyMjY1NDh8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by noor vasquez photo on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1590370082074-a48dcac07dd1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxmYW1pbHklMjB0b2dldGhlciUyMGhvbWUlMjBjaGlsZHJlbiUyMGxvdmUlMjBib25kfGVufDF8MHx8fDE3NzYyMjY1NDh8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by DICSON on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1516013474378-d6498f0d1434?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxmYW1pbHklMjB0b2dldGhlciUyMGhvbWUlMjBjaGlsZHJlbiUyMGxvdmUlMjBib25kfGVufDF8MHx8fDE3NzYyMjY1NDh8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Gift Habeshaw on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1654613698246-b6d44aef0fd5?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxmYW1pbHklMjB0b2dldGhlciUyMGhvbWUlMjBjaGlsZHJlbiUyMGxvdmUlMjBib25kfGVufDF8MHx8fDE3NzYyMjY1NDh8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by volant on Unsplash"
    }
  ],
  "sports": [
    {
      "url": "https://images.unsplash.com/photo-1670299160449-58cccb9545ff?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHx5b3V0aCUyMHNwb3J0cyUyMHRlYW0lMjBhdGhsZXRpY3MlMjBzdXBwb3J0fGVufDF8MHx8fDE3NzYyMjY1NDl8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Pedro Domingos on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1646743934955-010554191136?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHx5b3V0aCUyMHNwb3J0cyUyMHRlYW0lMjBhdGhsZXRpY3MlMjBzdXBwb3J0fGVufDF8MHx8fDE3NzYyMjY1NDl8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Konstantin Mishchenko on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1586154421967-3066c7a5c40a?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHx5b3V0aCUyMHNwb3J0cyUyMHRlYW0lMjBhdGhsZXRpY3MlMjBzdXBwb3J0fGVufDF8MHx8fDE3NzYyMjY1NDl8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Nguyen Thu Hoai on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1702333079527-7178960d483f?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHx5b3V0aCUyMHNwb3J0cyUyMHRlYW0lMjBhdGhsZXRpY3MlMjBzdXBwb3J0fGVufDF8MHx8fDE3NzYyMjY1NDl8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Lesli Whitecotton on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1696300064576-c072b92f4c55?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHx5b3V0aCUyMHNwb3J0cyUyMHRlYW0lMjBhdGhsZXRpY3MlMjBzdXBwb3J0fGVufDF8MHx8fDE3NzYyMjY1NDl8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Lesli Whitecotton on Unsplash"
    }
  ],
  "travel": [
    {
      "url": "https://images.unsplash.com/photo-1550623177-7c31a322de87?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHxqb3VybmV5JTIwdHJhdmVsJTIwaG9wZSUyMGFkdmVudHVyZSUyMHJvYWR8ZW58MXwwfHx8MTc3NjIyNjU1MHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Emma Dau on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1514673183591-1c2c0dbf3566?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHxqb3VybmV5JTIwdHJhdmVsJTIwaG9wZSUyMGFkdmVudHVyZSUyMHJvYWR8ZW58MXwwfHx8MTc3NjIyNjU1MHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Jeremy Bishop on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1513238164698-099ca7f34021?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHxqb3VybmV5JTIwdHJhdmVsJTIwaG9wZSUyMGFkdmVudHVyZSUyMHJvYWR8ZW58MXwwfHx8MTc3NjIyNjU1MHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Jeremy Bishop on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1603881669207-82be1849d585?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHxqb3VybmV5JTIwdHJhdmVsJTIwaG9wZSUyMGFkdmVudHVyZSUyMHJvYWR8ZW58MXwwfHx8MTc3NjIyNjU1MHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Tati y Adri on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1637580979113-58276fb5ff40?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHxqb3VybmV5JTIwdHJhdmVsJTIwaG9wZSUyMGFkdmVudHVyZSUyMHJvYWR8ZW58MXwwfHx8MTc3NjIyNjU1MHww&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Andrew Svk on Unsplash"
    }
  ],
  "volunteer": [
    {
      "url": "https://images.unsplash.com/photo-1764738130382-cc7a8eaf26c7?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHx2b2x1bnRlZXIlMjBzZXJ2aWNlJTIwY29tbXVuaXR5JTIwaGVscGluZyUyMGhhbmRzfGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Celine Ly on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668338-4c55a3bd0ce0?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHx2b2x1bnRlZXIlMjBzZXJ2aWNlJTIwY29tbXVuaXR5JTIwaGVscGluZyUyMGhhbmRzfGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668125-e154250f24bd?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHx2b2x1bnRlZXIlMjBzZXJ2aWNlJTIwY29tbXVuaXR5JTIwaGVscGluZyUyMGhhbmRzfGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599667717-27c61bcdd14b?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHx2b2x1bnRlZXIlMjBzZXJ2aWNlJTIwY29tbXVuaXR5JTIwaGVscGluZyUyMGhhbmRzfGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1758599668337-58bfa42683ce?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHx2b2x1bnRlZXIlMjBzZXJ2aWNlJTIwY29tbXVuaXR5JTIwaGVscGluZyUyMGhhbmRzfGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Vitaly Gariev on Unsplash"
    }
  ],
  "wishes": [
    {
      "url": "https://images.unsplash.com/photo-1726585389591-8851e3a8885c?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwxfHx3aXNoZXMlMjBkcmVhbSUyMGhvcGUlMjBzdGFycyUyMGNlbGVicmF0aW9ufGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Natalie Kinnear on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1609378622099-fa8349e293a5?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwyfHx3aXNoZXMlMjBkcmVhbSUyMGhvcGUlMjBzdGFycyUyMGNlbGVicmF0aW9ufGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by FlyD on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1609378622049-0b3e45d776f3?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHwzfHx3aXNoZXMlMjBkcmVhbSUyMGhvcGUlMjBzdGFycyUyMGNlbGVicmF0aW9ufGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by FlyD on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1628657773631-619dd152bea1?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw0fHx3aXNoZXMlMjBkcmVhbSUyMGhvcGUlMjBzdGFycyUyMGNlbGVicmF0aW9ufGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Alex Shute on Unsplash"
    },
    {
      "url": "https://images.unsplash.com/photo-1623638308822-7529ea3cf094?ixid=M3w5MjQ2Mjh8MHwxfHNlYXJjaHw1fHx3aXNoZXMlMjBkcmVhbSUyMGhvcGUlMjBzdGFycyUyMGNlbGVicmF0aW9ufGVufDF8MHx8fDE3NzYyMjY1NTF8MA&ixlib=rb-4.1.0&w=800&h=500&fit=crop&auto=format&q=80",
      "attribution": "Photo by Kier in Sight Archives on Unsplash"
    }
  ]
};

/**
 * Deterministic hash so the same campaign always picks the same fallback.
 */
function stableHash(str: string): number {
  let h = 0;
  for (let i = 0; i < str.length; i++) {
    h = ((h << 5) - h + str.charCodeAt(i)) | 0;
  }
  return Math.abs(h);
}

/**
 * Get a fallback image for a campaign whose hero image failed to load.
 *
 * @param category Campaign category (e.g. "medical", "memorial").
 * @param seed     Deterministic seed (campaign title) so the same campaign
 *                 always gets the same fallback image.
 * @returns A FallbackImage with url + attribution, or null if pool is empty.
 */
export function getCampaignFallback(
  category: string,
  seed: string,
): FallbackImage | null {
  const pool = POOL[category] ?? POOL['community'];
  if (!pool || pool.length === 0) return null;
  return pool[stableHash(seed) % pool.length]!;
}
