import type { CampaignCategory } from '@/types';

export const COMPETITOR_KEYWORDS = [
  'crowdfunding platform',
  'fundraising platform',
  'online fundraising',
  'fundraiser website',
  'fundraising site',
  'donation platform',
  'charity fundraising',
  'nonprofit fundraising',
  'crowdfunding campaign',
  'fundraising campaign',
  'donation page',
  'fundraising page',
  'donation form',
  'fundraising tools',
  'fundraise online',
  'start a fundraiser',
  'create a fundraiser',
  'launch a fundraising campaign',
  'raise money online',
  'raise money for a cause',
  'personal fundraising',
  'community fundraising',
  'peer-to-peer fundraising',
  'team fundraising',
  'social fundraising',
  'mobile fundraising',
  'share fundraiser link',
  'campaign updates',
  'fundraising dashboard',
  'fundraiser templates',
  'secure donations',
  'payment processing for donations',
  'donation receipts',
  'recurring donations',
  'fundraising goal',
  'goal meter',
  'supporter updates',
  'donor messages',
  'donor recognition',
  'zero platform fees',
  'no platform fees',
  'free fundraising platform',
  'free fundraising website',
  'transparent donations',
  'where donation money goes',
  'impact updates',
  'receipt-backed updates',
  'reviewed campaigns',
  'human-reviewed campaigns',
  'reviewed fundraisers',
  'reviewed crowdfunding',
  'trusted fundraising platform',
  'secure crowdfunding',
  'donation transparency',
  'fundraiser review',
  'campaign review',
  'medical fundraising',
  'medical fundraiser',
  'medical bills fundraiser',
  'hospital bills fundraiser',
  'surgery fundraiser',
  'cancer fundraiser',
  'emergency fundraiser',
  'emergency fundraising',
  'crisis relief fundraising',
  'disaster relief fundraising',
  'natural disaster fundraiser',
  'house fire fundraiser',
  'wildfire relief fundraiser',
  'flood relief fundraiser',
  'memorial fundraiser',
  'funeral fundraiser',
  'memorial fund',
  'funeral expenses fundraiser',
  'family emergency fundraiser',
  'family fundraising',
  'help with bills',
  'rent assistance fundraiser',
  'essential needs fundraiser',
  'veteran fundraiser',
  'veterans fundraising',
  'military family fundraiser',
  'first responder fundraiser',
  'education fundraiser',
  'tuition fundraiser',
  'scholarship fundraiser',
  'animal fundraiser',
  'pet fundraiser',
  'vet bills fundraiser',
  'animal rescue fundraiser',
  'charity fundraiser',
  'faith based fundraiser',
  'church fundraiser',
  'community project fundraiser',
  'small business fundraiser',
  'event fundraiser',
  'sports fundraiser',
  'environmental fundraiser',
  'volunteer fundraiser',
  'wish fundraiser',
] as const;

type Keyword = (typeof COMPETITOR_KEYWORDS)[number];

const keywordGroups = {
  core: [
    'crowdfunding platform',
    'fundraising platform',
    'online fundraising',
    'fundraiser website',
    'fundraising site',
    'donation platform',
    'reviewed crowdfunding',
    'reviewed campaigns',
    'human-reviewed campaigns',
    'zero platform fees',
    'donation transparency',
    'impact updates',
  ],
  start: [
    'start a fundraiser',
    'create a fundraiser',
    'launch a fundraising campaign',
    'raise money online',
    'raise money for a cause',
    'personal fundraising',
    'fundraise online',
    'share fundraiser link',
    'fundraising goal',
    'campaign review',
  ],
  campaigns: [
    'crowdfunding campaign',
    'fundraising campaign',
    'fundraising page',
    'donation page',
    'medical fundraiser',
    'emergency fundraiser',
    'memorial fundraiser',
    'family emergency fundraiser',
    'disaster relief fundraising',
    'reviewed fundraisers',
  ],
  trust: [
    'secure donations',
    'payment processing for donations',
    'donation receipts',
    'transparent donations',
    'where donation money goes',
    'receipt-backed updates',
    'trusted fundraising platform',
    'secure crowdfunding',
    'fundraiser review',
    'supporter updates',
  ],
  medical: [
    'medical fundraising',
    'medical fundraiser',
    'medical bills fundraiser',
    'hospital bills fundraiser',
    'surgery fundraiser',
    'cancer fundraiser',
  ],
  emergency: [
    'emergency fundraiser',
    'emergency fundraising',
    'crisis relief fundraising',
    'house fire fundraiser',
    'help with bills',
    'family emergency fundraiser',
  ],
  disaster: [
    'disaster relief fundraising',
    'natural disaster fundraiser',
    'house fire fundraiser',
    'wildfire relief fundraiser',
    'flood relief fundraiser',
  ],
  memorial: [
    'memorial fundraiser',
    'funeral fundraiser',
    'memorial fund',
    'funeral expenses fundraiser',
  ],
  family: [
    'family emergency fundraiser',
    'family fundraising',
    'help with bills',
    'rent assistance fundraiser',
    'essential needs fundraiser',
  ],
  nonprofit: [
    'charity fundraising',
    'nonprofit fundraising',
    'charity fundraiser',
    'community fundraising',
    'community project fundraiser',
    'volunteer fundraiser',
  ],
  platform: [
    'donation form',
    'fundraising tools',
    'fundraising dashboard',
    'fundraiser templates',
    'mobile fundraising',
    'campaign updates',
    'donor messages',
    'donor recognition',
    'goal meter',
  ],
  donor: [
    'donation page',
    'recurring donations',
    'secure donations',
    'donation receipts',
    'donor messages',
    'donor recognition',
    'supporter updates',
  ],
} satisfies Record<string, readonly Keyword[]>;

const categoryKeywordMap: Partial<Record<CampaignCategory, readonly Keyword[]>> = {
  medical: keywordGroups.medical,
  emergency: keywordGroups.emergency,
  disaster: keywordGroups.disaster,
  memorial: keywordGroups.memorial,
  family: keywordGroups.family,
  'essential-needs': keywordGroups.family,
  charity: keywordGroups.nonprofit,
  community: ['community fundraising', 'community project fundraiser', 'charity fundraiser', 'raise money for a cause'],
  volunteer: ['volunteer fundraiser', 'community fundraising', 'community project fundraiser', 'raise money for a cause'],
  veterans: ['veteran fundraiser', 'veterans fundraising', 'medical fundraiser', 'help with bills'],
  military: ['military family fundraiser', 'veteran fundraiser', 'family emergency fundraiser', 'help with bills'],
  'first-responders': ['first responder fundraiser', 'emergency fundraiser', 'family emergency fundraiser', 'help with bills'],
  education: ['education fundraiser', 'tuition fundraiser', 'scholarship fundraiser', 'raise money online'],
  animal: ['animal fundraiser', 'pet fundraiser', 'vet bills fundraiser', 'animal rescue fundraiser'],
  faith: ['faith based fundraiser', 'church fundraiser', 'charity fundraiser', 'community fundraising'],
  business: ['small business fundraiser', 'emergency fundraiser', 'community fundraising', 'raise money online'],
  event: ['event fundraiser', 'community fundraising', 'charity fundraising', 'raise money for a cause'],
  sports: ['sports fundraiser', 'team fundraising', 'raise money online', 'fundraising campaign'],
  environment: ['environmental fundraiser', 'community project fundraiser', 'charity fundraiser', 'volunteer fundraiser'],
  wishes: ['wish fundraiser', 'personal fundraising', 'community fundraising', 'raise money for a cause'],
};

export function seoKeywords(...groups: Array<keyof typeof keywordGroups>): string[] {
  return Array.from(new Set(groups.flatMap((group) => keywordGroups[group])));
}

export function categorySeoKeywords(category: CampaignCategory): string[] {
  return Array.from(new Set([
    ...keywordGroups.campaigns,
    ...(categoryKeywordMap[category] ?? []),
    ...keywordGroups.trust.slice(0, 4),
  ]));
}
