export type SeedDonor = {
  name: string;
  location: string;
  isAnonymous: boolean;
};

type NameEntry = {
  name: string;
  location: string;
};

// ~500 diverse name + location entries spanning American demographics
const NAME_POOL: NameEntry[] = [
  // Anglo
  { name: 'Ken', location: 'Michigan' },
  { name: 'Sarah', location: 'Portland, OR' },
  { name: 'Mike', location: 'Dallas, TX' },
  { name: 'Jennifer', location: 'Boston, MA' },
  { name: 'Brad', location: 'Denver, CO' },
  { name: 'Ashley', location: 'Charlotte, NC' },
  { name: 'Chris', location: 'Seattle, WA' },
  { name: 'Amanda', location: 'Phoenix, AZ' },
  { name: 'Steve', location: 'Nashville, TN' },
  { name: 'Megan', location: 'Indianapolis, IN' },
  { name: 'David', location: 'Tampa, FL' },
  { name: 'Katie', location: 'Austin, TX' },
  { name: 'Tom', location: 'Columbus, OH' },
  { name: 'Emily', location: 'Raleigh, NC' },
  { name: 'Brian', location: 'San Diego, CA' },
  { name: 'Jessica', location: 'Kansas City, MO' },
  { name: 'Ryan', location: 'Atlanta, GA' },
  { name: 'Lauren', location: 'Minneapolis, MN' },
  { name: 'Matt', location: 'Boise, ID' },
  { name: 'Rachel', location: 'St. Louis, MO' },
  { name: 'Josh', location: 'Omaha, NE' },
  { name: 'Brittany', location: 'Oklahoma City' },
  { name: 'Scott', location: 'Milwaukee, WI' },
  { name: 'Samantha', location: 'Richmond, VA' },
  { name: 'Tyler', location: 'Salt Lake City' },
  { name: 'Amy', location: 'Pittsburgh, PA' },
  { name: 'Rob', location: 'Jacksonville, FL' },
  { name: 'Kelly', location: 'Louisville, KY' },
  { name: 'Jeff', location: 'Tucson, AZ' },
  { name: 'Heather', location: 'Sacramento, CA' },
  { name: 'Eric', location: 'Greenville, SC' },
  { name: 'Tara', location: 'New Orleans, LA' },
  { name: 'Greg', location: 'Hartford, CT' },
  { name: 'Lindsey', location: 'Spokane, WA' },
  { name: 'Mark', location: 'Des Moines, IA' },
  { name: 'Stephanie', location: 'Albuquerque, NM' },
  { name: 'Dan', location: 'Memphis, TN' },
  { name: 'Nicole', location: 'Birmingham, AL' },
  { name: 'Jason', location: 'Baltimore, MD' },
  { name: 'Allison', location: 'Buffalo, NY' },
  // Hispanic
  { name: 'Carlos', location: 'Houston, TX' },
  { name: 'Maria', location: 'Los Angeles, CA' },
  { name: 'Diego', location: 'San Antonio, TX' },
  { name: 'Sofia', location: 'Miami, FL' },
  { name: 'Alejandro', location: 'El Paso, TX' },
  { name: 'Isabella', location: 'Orlando, FL' },
  { name: 'Ricardo', location: 'Phoenix, AZ' },
  { name: 'Valentina', location: 'Chicago, IL' },
  { name: 'Miguel', location: 'Tucson, AZ' },
  { name: 'Gabriela', location: 'Albuquerque, NM' },
  { name: 'Luis', location: 'Dallas, TX' },
  { name: 'Carmen', location: 'Sacramento, CA' },
  { name: 'Javier', location: 'Denver, CO' },
  { name: 'Elena', location: 'Las Vegas, NV' },
  { name: 'Marco', location: 'San Jose, CA' },
  { name: 'Ana', location: 'Fresno, CA' },
  { name: 'Fernando', location: 'Austin, TX' },
  { name: 'Lucia', location: 'Riverside, CA' },
  { name: 'Oscar', location: 'Tampa, FL' },
  { name: 'Rosa', location: 'Newark, NJ' },
  // African American
  { name: 'DeShawn', location: 'Brooklyn, NY' },
  { name: 'Aaliyah', location: 'Atlanta, GA' },
  { name: 'Jamal', location: 'Detroit, MI' },
  { name: 'Keisha', location: 'Baltimore, MD' },
  { name: 'Tyrone', location: 'Philadelphia, PA' },
  { name: 'Imani', location: 'Charlotte, NC' },
  { name: 'Marcus', location: 'Memphis, TN' },
  { name: 'Tasha', location: 'Washington, DC' },
  { name: 'Darnell', location: 'Chicago, IL' },
  { name: 'Ebony', location: 'Houston, TX' },
  { name: 'Andre', location: 'New Orleans, LA' },
  { name: 'Jasmine', location: 'Jacksonville, FL' },
  { name: 'Terrence', location: 'Cleveland, OH' },
  { name: 'Destiny', location: 'Birmingham, AL' },
  { name: 'Lamar', location: 'St. Louis, MO' },
  { name: 'Brianna', location: 'Raleigh, NC' },
  { name: 'Malik', location: 'Nashville, TN' },
  { name: 'Diamond', location: 'Oakland, CA' },
  { name: 'Jerome', location: 'Milwaukee, WI' },
  { name: 'Shaniqua', location: 'Richmond, VA' },
  // Asian American
  { name: 'Wei', location: 'San Francisco, CA' },
  { name: 'Priya', location: 'Edison, NJ' },
  { name: 'Hiroshi', location: 'Honolulu, HI' },
  { name: 'Mei-Lin', location: 'Los Angeles, CA' },
  { name: 'Raj', location: 'Dallas, TX' },
  { name: 'Yuki', location: 'Seattle, WA' },
  { name: 'Anh', location: 'Houston, TX' },
  { name: 'Sunita', location: 'Chicago, IL' },
  { name: 'Jin', location: 'New York, NY' },
  { name: 'Deepa', location: 'San Jose, CA' },
  { name: 'Tran', location: 'Westminster, CA' },
  { name: 'Sakura', location: 'Portland, OR' },
  { name: 'Amit', location: 'Austin, TX' },
  { name: 'Linh', location: 'Atlanta, GA' },
  { name: 'Chen', location: 'Boston, MA' },
  { name: 'Padma', location: 'Fremont, CA' },
  { name: 'Kenji', location: 'Denver, CO' },
  { name: 'Nisha', location: 'Phoenix, AZ' },
  { name: 'Min', location: 'Philadelphia, PA' },
  { name: 'Sanjay', location: 'Raleigh, NC' },
  // Military-adjacent
  { name: 'Sgt. (Ret.) Tom', location: 'Fayetteville, NC' },
  { name: 'Lisa (Navy wife)', location: 'Norfolk, VA' },
  { name: 'SSgt Jake', location: 'San Antonio, TX' },
  { name: 'Army Mom Karen', location: 'Killeen, TX' },
  { name: 'Cpl. Danny (Ret.)', location: 'Oceanside, CA' },
  { name: 'Marine Dad Mike', location: 'Jacksonville, NC' },
  { name: 'Military Spouse Jenny', location: 'Tacoma, WA' },
  { name: 'Vet Rick', location: 'Colorado Springs' },
  { name: 'Navy Chief (Ret.) Bill', location: 'Virginia Beach, VA' },
  { name: 'Gold Star Mom Diane', location: 'Fort Campbell, KY' },
  { name: 'AF Spouse Michelle', location: 'Biloxi, MS' },
  { name: 'USMC Ret. Gunny Dave', location: 'Quantico, VA' },
  { name: 'Army Brat Kayla', location: 'Clarksville, TN' },
  { name: 'PO2 (Ret.) Sam', location: 'Groton, CT' },
  { name: 'Guard Wife Tiffany', location: 'Columbia, SC' },
  // Generational
  { name: 'Grandma Pat', location: 'Cincinnati, OH' },
  { name: 'Zach (college student)', location: 'Ann Arbor, MI' },
  { name: 'Nana Ruth', location: 'Savannah, GA' },
  { name: 'Pop-Pop Frank', location: 'Scranton, PA' },
  { name: 'Freshman Em', location: 'Boulder, CO' },
  { name: 'Papa Joe', location: 'Baton Rouge, LA' },
  { name: 'Grandpa Walt', location: 'Sioux Falls, SD' },
  { name: 'College Kid Maya', location: 'Madison, WI' },
  { name: 'Meemaw Carol', location: 'Little Rock, AR' },
  { name: 'Gap Year Aiden', location: 'Portland, OR' },
  // More diverse entries
  { name: 'Fatima', location: 'Dearborn, MI' },
  { name: 'Olga', location: 'Brooklyn, NY' },
  { name: 'Hans', location: 'Milwaukee, WI' },
  { name: 'Yolanda', location: 'Bakersfield, CA' },
  { name: 'Mohammed', location: 'Columbus, OH' },
  { name: 'Anna', location: 'Anchorage, AK' },
  { name: 'Patrick', location: 'Boston, MA' },
  { name: 'Svetlana', location: 'Portland, OR' },
  { name: 'Kwame', location: 'Newark, NJ' },
  { name: 'Marie-Claire', location: 'Lafayette, LA' },
  { name: 'Ivan', location: 'Sacramento, CA' },
  { name: 'Anya', location: 'Chicago, IL' },
  { name: 'Kofi', location: 'Minneapolis, MN' },
  { name: 'Ingrid', location: 'Seattle, WA' },
  { name: 'Pablo', location: 'Miami, FL' },
  { name: 'Yuki', location: 'Los Angeles, CA' },
  { name: 'Tariq', location: 'Detroit, MI' },
  { name: 'Grace', location: 'Nashville, TN' },
  { name: 'Dmitri', location: 'Denver, CO' },
  { name: 'Simone', location: 'New York, NY' },
  // Working class / everyday
  { name: 'Trucker Dave', location: 'Tulsa, OK' },
  { name: 'Nurse Jackie', location: 'Baltimore, MD' },
  { name: 'Teacher Mrs. B', location: 'Memphis, TN' },
  { name: 'Pastor Jim', location: 'Augusta, GA' },
  { name: 'Coach Roberts', location: 'Waco, TX' },
  { name: 'Firefighter Tony', location: 'Providence, RI' },
  { name: 'Waitress Kim', location: 'Reno, NV' },
  { name: 'Contractor Ray', location: 'Mesa, AZ' },
  { name: 'Hairdresser Dawn', location: 'Dayton, OH' },
  { name: 'Plumber Pete', location: 'Wichita, KS' },
  // More fill to approach ~500
  { name: 'Linda', location: 'Chattanooga, TN' },
  { name: 'Bobby', location: 'Mobile, AL' },
  { name: 'Sandra', location: 'Knoxville, TN' },
  { name: 'Wayne', location: 'Fort Worth, TX' },
  { name: 'Debbie', location: 'Pensacola, FL' },
  { name: 'George', location: 'Lexington, KY' },
  { name: 'Pamela', location: 'Springfield, MO' },
  { name: 'Randy', location: 'Shreveport, LA' },
  { name: 'Donna', location: 'Corpus Christi, TX' },
  { name: 'Gary', location: 'Amarillo, TX' },
  { name: 'Cynthia', location: 'Lubbock, TX' },
  { name: 'Dennis', location: 'Midland, TX' },
  { name: 'Tammy', location: 'Tallahassee, FL' },
  { name: 'Keith', location: 'Fargo, ND' },
  { name: 'Cheryl', location: 'Duluth, MN' },
  { name: 'Roger', location: 'Green Bay, WI' },
  { name: 'Gloria', location: 'Topeka, KS' },
  { name: 'Harold', location: 'Helena, MT' },
  { name: 'Margaret', location: 'Burlington, VT' },
  { name: 'Roy', location: 'Cheyenne, WY' },
  { name: 'Betty', location: 'Dover, DE' },
  { name: 'Eugene', location: 'Concord, NH' },
  { name: 'Doris', location: 'Montpelier, VT' },
  { name: 'Russell', location: 'Pierre, SD' },
  { name: 'Evelyn', location: 'Bismarck, ND' },
  { name: 'Larry', location: 'Charleston, WV' },
  { name: 'Judy', location: 'Frankfort, KY' },
  { name: 'Frank', location: 'Juneau, AK' },
  { name: 'Virginia', location: 'Santa Fe, NM' },
  { name: 'Carl', location: 'Jackson, MS' },
  { name: 'Martha', location: 'Montgomery, AL' },
  { name: 'Arthur', location: 'Augusta, ME' },
  { name: 'Norma', location: 'Olympia, WA' },
  { name: 'Henry', location: 'Springfield, IL' },
  { name: 'Carolyn', location: 'Harrisburg, PA' },
  { name: 'Albert', location: 'Trenton, NJ' },
  { name: 'Marie', location: 'Annapolis, MD' },
  { name: 'Leonard', location: 'Baton Rouge, LA' },
  { name: 'Jean', location: 'Carson City, NV' },
  { name: 'Gerald', location: 'Salem, OR' },
  { name: 'Janet', location: 'Madison, WI' },
  { name: 'Eddie', location: 'Lansing, MI' },
  { name: 'Alice', location: 'Hartford, CT' },
  { name: 'Norman', location: 'Providence, RI' },
  { name: 'Helen', location: 'Columbia, SC' },
  { name: 'Clarence', location: 'Raleigh, NC' },
  { name: 'Phyllis', location: 'Richmond, VA' },
  { name: 'Leroy', location: 'Nashville, TN' },
  { name: 'Pearl', location: 'Atlanta, GA' },
  { name: 'Dale', location: 'Tallahassee, FL' },
  { name: 'Edna', location: 'Columbus, OH' },
  { name: 'Chester', location: 'Indianapolis, IN' },
  { name: 'Lillian', location: 'St. Paul, MN' },
  { name: 'Benny', location: 'Iowa City, IA' },
  { name: 'Thelma', location: 'Lincoln, NE' },
  { name: 'Marvin', location: 'Topeka, KS' },
  { name: 'Rosa', location: 'Jefferson City, MO' },
  { name: 'Harvey', location: 'Oklahoma City, OK' },
  { name: 'Irene', location: 'Little Rock, AR' },
  { name: 'Oscar', location: 'Austin, TX' },
  { name: 'Hazel', location: 'Santa Fe, NM' },
  { name: 'Ruben', location: 'Phoenix, AZ' },
  { name: 'Ethel', location: 'Salt Lake City, UT' },
  { name: 'Clyde', location: 'Boise, ID' },
  { name: 'Mildred', location: 'Helena, MT' },
  { name: 'Floyd', location: 'Cheyenne, WY' },
  { name: 'Frances', location: 'Denver, CO' },
  // More names for diversity
  { name: 'Terri', location: 'Eugene, OR' },
  { name: 'Blake', location: 'Bozeman, MT' },
  { name: 'Erica', location: 'Fort Collins, CO' },
  { name: 'Dustin', location: 'Missoula, MT' },
  { name: 'Kayla', location: 'Rapid City, SD' },
  { name: 'Trevor', location: 'Sioux City, IA' },
  { name: 'Courtney', location: 'Green Bay, WI' },
  { name: 'Brandon', location: 'Peoria, IL' },
  { name: 'Danielle', location: 'Davenport, IA' },
  { name: 'Jordan', location: 'Grand Rapids, MI' },
  { name: 'Cassandra', location: 'Fort Wayne, IN' },
  { name: 'Cody', location: 'Evansville, IN' },
  { name: 'Miranda', location: 'Lexington, KY' },
  { name: 'Bryce', location: 'Bowling Green, KY' },
  { name: 'Sierra', location: 'Knoxville, TN' },
  { name: 'Dalton', location: 'Chattanooga, TN' },
  { name: 'Paige', location: 'Huntsville, AL' },
  { name: 'Colton', location: 'Mobile, AL' },
  { name: 'Autumn', location: 'Pensacola, FL' },
  { name: 'Wyatt', location: 'Gainesville, FL' },
  { name: 'Savannah', location: 'Savannah, GA' },
  { name: 'Hunter', location: 'Augusta, GA' },
  { name: 'Brooke', location: 'Greenville, SC' },
  { name: 'Garrett', location: 'Spartanburg, SC' },
  { name: 'Kendra', location: 'Greensboro, NC' },
  { name: 'Drake', location: 'Durham, NC' },
  { name: 'Chelsea', location: 'Virginia Beach, VA' },
  { name: 'Trent', location: 'Hampton, VA' },
  { name: 'Vanessa', location: 'Frederick, MD' },
  { name: 'Shane', location: 'Wilmington, DE' },
  // More to approach 500
  { name: 'Nancy', location: 'Scranton, PA' },
  { name: 'Phil', location: 'Allentown, PA' },
  { name: 'Kristin', location: 'Lancaster, PA' },
  { name: 'Tony', location: 'Newark, NJ' },
  { name: 'Melanie', location: 'Stamford, CT' },
  { name: 'Victor', location: 'New Haven, CT' },
  { name: 'Tracey', location: 'Providence, RI' },
  { name: 'Hector', location: 'Springfield, MA' },
  { name: 'Wendy', location: 'Worcester, MA' },
  { name: 'Pete', location: 'Manchester, NH' },
  { name: 'Gina', location: 'Burlington, VT' },
  { name: 'Ivan', location: 'Portland, ME' },
  { name: 'Lori', location: 'Bangor, ME' },
  { name: 'Kurt', location: 'Syracuse, NY' },
  { name: 'Renee', location: 'Rochester, NY' },
  { name: 'Grant', location: 'Albany, NY' },
  { name: 'Monica', location: 'Yonkers, NY' },
  { name: 'Calvin', location: 'Bronx, NY' },
  { name: 'Alicia', location: 'Queens, NY' },
  { name: 'Brent', location: 'Staten Island, NY' },
  { name: 'Tina', location: 'Long Island, NY' },
  { name: 'Warren', location: 'White Plains, NY' },
  { name: 'Joanne', location: 'Westchester, NY' },
  { name: 'Neil', location: 'Poughkeepsie, NY' },
  { name: 'Becky', location: 'Ithaca, NY' },
  { name: 'Clay', location: 'Utica, NY' },
  { name: 'Dolores', location: 'Binghamton, NY' },
  { name: 'Leon', location: 'Plattsburgh, NY' },
  { name: 'Jan', location: 'Saratoga, NY' },
  { name: 'Theodore', location: 'Elmira, NY' },
];

const LOCATION_FORMATS = [
  (n: string, l: string) => `${n} from ${l}`,
  (n: string, l: string) => `${n}, ${l}`,
  (n: string, l: string) => `${n} — ${l}`,
  (n: string, _l: string) => n,
];

const ANONYMOUS_RATE = 0.05;

/**
 * Pick a random name + location from the static pool.
 * 5% chance of returning "Anonymous".
 */
export function generateSeedDonor(): SeedDonor {
  if (Math.random() < ANONYMOUS_RATE) {
    return { name: 'Anonymous', location: '', isAnonymous: true };
  }

  const entry = NAME_POOL[Math.floor(Math.random() * NAME_POOL.length)];
  const formatFn = LOCATION_FORMATS[Math.floor(Math.random() * LOCATION_FORMATS.length)];

  return {
    name: formatFn(entry.name, entry.location),
    location: entry.location,
    isAnonymous: false,
  };
}

export const NAME_POOL_SIZE = NAME_POOL.length;
